# Generated by Django 3.2.5 on 2021-07-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('mail', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
