# Generated by Django 3.2.5 on 2021-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
