# Generated by Django 3.2.5 on 2021-07-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0002_album_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField()),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_label.location')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_label.artist')),
                ('id_concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_label.concert')),
            ],
            options={
                'unique_together': {('id_artist', 'id_concert')},
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_label.artist')),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_label.song')),
            ],
            options={
                'unique_together': {('id_song', 'id_artist')},
            },
        ),
    ]
