# Generated by Django 3.2.5 on 2021-08-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0002_auto_20210811_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboration',
            old_name='id_artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='collaboration',
            old_name='id_song',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='id_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='id_artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='id_concert',
            new_name='concert',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='id_album',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='id_artist',
            new_name='artist',
        ),
        migrations.AlterUniqueTogether(
            name='collaboration',
            unique_together={('song', 'artist')},
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('artist', 'concert')},
        ),
    ]
