# Generated by Django 3.2.5 on 2021-07-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0003_collaboration_concert_contract_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='sex',
            new_name='gender',
        ),
    ]
