# Generated by Django 3.2.5 on 2021-07-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0005_alter_artist_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='song',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
