# Generated by Django 3.2.5 on 2021-07-31 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0006_auto_20210731_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='record_label.album'),
        ),
    ]
