# Generated by Django 3.2.5 on 2021-07-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0007_alter_song_id_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='publish_date',
            new_name='concert_date',
        ),
    ]
