# Generated by Django 3.2.5 on 2021-07-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0008_rename_publish_date_concert_concert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
